### PR TITLE
Some basic VM creation tests

### PR DESCRIPTION
**Pull request by jerith**
Before I can work on this code, it needs some tests.

### CODE REVIEW

**Comment by jerith** [comment]
This isn't ready to land yet, but some initial review would be useful.

**Comment by calston** [comment]
:+1:

**Comment by smn** [comment]
:+1: and good grief how horrible is xmlrpc

**Comment by jerith** [comment]
Ready for review.

**Comment by jerith** [comment]
XMLRPC isn't *that* horrible in the grand scheme of things. Some of the horribleness there is me faking HTTP and much of the rest is a mismatch between XMLRPC's class/method model and the way I'm tracking fake XenServer state.

**Comment by calston** [comment]
:+1:

**Pull request merged**
