### PR TITLE
Tooling updates

### PR DESCRIPTION
**Pull request by JayH5**
The usual up-to-date flake8 + Travis + pytest + coverage, etc.

### CODE REVIEW

**Comment by jerith** [comment]
Can you adjust the coverage target so we get a green build?

**Comment by jerith** [comment]
Looks okay, but I'm not entirely sure that the sideloader builds will still be happy after these changes. We'll have to watch after merging and make sure it's okay.

@ProfMerlin: Do you have any thoughts on this?

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[skeleton/wsgi.py, line 21 at r1](https://reviewable.io:443/reviews/praekeltfoundation/xenzen/19#-KbFvOBd9hnn3Xf5-UXl:-KbFvOBd9hnn3Xf5-UXm:b-qtl88m) ([raw file](https://github.com/praekeltfoundation/xenzen/blob/b71030c7bb10a372245b079edd0ca701cb2ff7cf/skeleton/wsgi.py#L21)):*
> ```Python
> # file. This includes Django's development server, if the WSGI_APPLICATION
> # setting points here.
> from django.core.wsgi import get_wsgi_application
> ```

Why did this move?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/praekeltfoundation/xenzen/19#-:-KbFz71-6nGGPvzoesK9:b-wo3p9s)*

**Comment by JayH5** [comment]
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[skeleton/wsgi.py, line 21 at r1](https://reviewable.io:443/reviews/praekeltfoundation/xenzen/19#-KbFvOBd9hnn3Xf5-UXl:-KbFztbmE0IaBX4olHq_:b8a2dve) ([raw file](https://github.com/praekeltfoundation/xenzen/blob/b71030c7bb10a372245b079edd0ca701cb2ff7cf/skeleton/wsgi.py#L21)):*
<details><summary><i>Previously, jerith (Jeremy Thurgood) wrote…</i></summary><blockquote>

Why did this move?
</blockquote></details>

flake8 complains if the imports don't all happen first. I checked, and the default wsgi.py generated by Django (although, 1.10) does things just like this: https://github.com/praekeltfoundation/docker-django-bootstrap/blob/develop/example/mysite/wsgi.py

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/praekeltfoundation/xenzen/19)*

**Comment by jerith** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[codecov.yml, line 3 at r2](https://reviewable.io:443/reviews/praekeltfoundation/xenzen/19#-KbG1SGRge2PVMWZmbWX:-KbG1SGRge2PVMWZmbWY:b91t8ax) ([raw file](https://github.com/praekeltfoundation/xenzen/blob/3748c10d54d10f4b61fc9bd7eee2e2249ebed19b/codecov.yml#L3)):*
> ```YAML
> coverage:
>   # We don't have great coverage yet... allow down to 50%
>   range: "50...100"
> ```

I think you want this:
```yaml
coverage:
  status:
    default:
      target: 50
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/praekeltfoundation/xenzen/19)*

**Comment by jerith** [comment]
LGTM :shipit: :beers: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/praekeltfoundation/xenzen/19#-:-KbG46h5-nMHrexI4S5F:bx73dsf)*

**Comment by ProfMerlin** [comment]
👍 from me

**Pull request merged**
